# Generated by Django 3.2.5 on 2021-07-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=70)),
                ('cgpa', models.FloatField()),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
