# Generated by Django 3.2.5 on 2021-07-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_pythonprojects_webproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webproject',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
