# Generated by Django 3.2.5 on 2021-07-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_webproject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonprojects',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='webproject',
            name='description',
            field=models.TextField(),
        ),
    ]
