# Generated by Django 3.2.5 on 2021-07-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20210714_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonprojects',
            name='collapseid',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='webproject',
            name='collapseid',
            field=models.IntegerField(default=1),
        ),
    ]
