# Generated by Django 3.2.5 on 2021-07-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20210714_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonprojects',
            name='collapseid',
            field=models.CharField(default='a', max_length=5),
        ),
        migrations.AlterField(
            model_name='webproject',
            name='collapseid',
            field=models.CharField(default='a', max_length=5),
        ),
    ]
